version: "3"
services:
  mongodb-express:
    container_name: mongodb-express
    image: mongo-express:latest
    links:
      - mongodb:mongo
    ports:
      - "8081:8081"
    logging:
      driver: "none"
