version: "3"
services:
  test:
    container_name: test
    command: npm run test:docker
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
     - app
     - mongodb
    environment:
      - TARGET=http://app:3000
 